// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminCountUserURLs = `-- name: AdminCountUserURLs :one
SELECT COUNT(*)::bigint FROM short_urls
WHERE owner_type = 'user' AND owner_id = $1
`

func (q *Queries) AdminCountUserURLs(ctx context.Context, ownerID string) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountUserURLs, ownerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const adminCountUsers = `-- name: AdminCountUsers :one
SELECT COUNT(*)::bigint FROM users
`

func (q *Queries) AdminCountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountUsers)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const adminGetPlatformStats = `-- name: AdminGetPlatformStats :one
SELECT
    (SELECT COUNT(*)::bigint FROM users) AS total_users,
    (SELECT COUNT(*)::bigint FROM short_urls WHERE is_deleted = false) AS total_urls,
    (SELECT COUNT(*)::bigint FROM clicks) AS total_clicks
`

type AdminGetPlatformStatsRow struct {
	TotalUsers  int64 `json:"total_users"`
	TotalUrls   int64 `json:"total_urls"`
	TotalClicks int64 `json:"total_clicks"`
}

func (q *Queries) AdminGetPlatformStats(ctx context.Context) (AdminGetPlatformStatsRow, error) {
	row := q.db.QueryRow(ctx, adminGetPlatformStats)
	var i AdminGetPlatformStatsRow
	err := row.Scan(&i.TotalUsers, &i.TotalUrls, &i.TotalClicks)
	return i, err
}

const adminGetUserURLs = `-- name: AdminGetUserURLs :many
SELECT
    s.id,
    s.code,
    s.long_url,
    s.name,
    s.is_active,
    s.is_deleted,
    s.created_at,
    s.expires_at,
    COALESCE(COUNT(c.id), 0)::bigint AS click_count
FROM short_urls s
LEFT JOIN clicks c ON c.short_url_id = s.id
WHERE s.owner_type = 'user' AND s.owner_id = $1
GROUP BY s.id
ORDER BY click_count DESC
LIMIT $2 OFFSET $3
`

type AdminGetUserURLsParams struct {
	OwnerID string `json:"owner_id"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type AdminGetUserURLsRow struct {
	ID         int64              `json:"id"`
	Code       string             `json:"code"`
	LongUrl    string             `json:"long_url"`
	Name       pgtype.Text        `json:"name"`
	IsActive   bool               `json:"is_active"`
	IsDeleted  bool               `json:"is_deleted"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	ClickCount int64              `json:"click_count"`
}

func (q *Queries) AdminGetUserURLs(ctx context.Context, arg AdminGetUserURLsParams) ([]AdminGetUserURLsRow, error) {
	rows, err := q.db.Query(ctx, adminGetUserURLs, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminGetUserURLsRow{}
	for rows.Next() {
		var i AdminGetUserURLsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.LongUrl,
			&i.Name,
			&i.IsActive,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.ClickCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminGetUsersByTier = `-- name: AdminGetUsersByTier :many
SELECT tier, COUNT(*)::bigint AS count
FROM users
GROUP BY tier
`

type AdminGetUsersByTierRow struct {
	Tier  SubscriptionTier `json:"tier"`
	Count int64            `json:"count"`
}

func (q *Queries) AdminGetUsersByTier(ctx context.Context) ([]AdminGetUsersByTierRow, error) {
	rows, err := q.db.Query(ctx, adminGetUsersByTier)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminGetUsersByTierRow{}
	for rows.Next() {
		var i AdminGetUsersByTierRow
		if err := rows.Scan(&i.Tier, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListUsers = `-- name: AdminListUsers :many
SELECT
    u.id,
    u.email,
    u.name,
    u.tier,
    u.login_type,
    u.created_at,
    COUNT(DISTINCT s.id)::bigint AS url_count,
    COALESCE(SUM(click_counts.total), 0)::bigint AS total_clicks
FROM users u
LEFT JOIN short_urls s ON s.owner_type = 'user' AND s.owner_id = u.id::text AND s.is_deleted = false
LEFT JOIN (
    SELECT short_url_id, COUNT(*)::bigint AS total
    FROM clicks
    GROUP BY short_url_id
) click_counts ON click_counts.short_url_id = s.id
GROUP BY u.id
ORDER BY total_clicks DESC
LIMIT $1 OFFSET $2
`

type AdminListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type AdminListUsersRow struct {
	ID          pgtype.UUID        `json:"id"`
	Email       string             `json:"email"`
	Name        pgtype.Text        `json:"name"`
	Tier        SubscriptionTier   `json:"tier"`
	LoginType   int16              `json:"login_type"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UrlCount    int64              `json:"url_count"`
	TotalClicks int64              `json:"total_clicks"`
}

func (q *Queries) AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]AdminListUsersRow, error) {
	rows, err := q.db.Query(ctx, adminListUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListUsersRow{}
	for rows.Next() {
		var i AdminListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Tier,
			&i.LoginType,
			&i.CreatedAt,
			&i.UrlCount,
			&i.TotalClicks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
