// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countClicksByShortURLID = `-- name: CountClicksByShortURLID :one
SELECT COUNT(*) FROM clicks WHERE short_url_id = $1
`

func (q *Queries) CountClicksByShortURLID(ctx context.Context, shortUrlID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countClicksByShortURLID, shortUrlID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUniqueClicksByShortURLID = `-- name: CountUniqueClicksByShortURLID :one
SELECT COUNT(*) FROM clicks WHERE short_url_id = $1 AND is_unique = TRUE
`

func (q *Queries) CountUniqueClicksByShortURLID(ctx context.Context, shortUrlID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUniqueClicksByShortURLID, shortUrlID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getClicksByBrowser = `-- name: GetClicksByBrowser :many
SELECT browser, COUNT(*) as clicks FROM clicks WHERE short_url_id = $1 AND clicked_at >= $2 GROUP BY browser ORDER BY clicks DESC
`

type GetClicksByBrowserParams struct {
	ShortUrlID int64              `json:"short_url_id"`
	ClickedAt  pgtype.Timestamptz `json:"clicked_at"`
}

type GetClicksByBrowserRow struct {
	Browser pgtype.Text `json:"browser"`
	Clicks  int64       `json:"clicks"`
}

func (q *Queries) GetClicksByBrowser(ctx context.Context, arg GetClicksByBrowserParams) ([]GetClicksByBrowserRow, error) {
	rows, err := q.db.Query(ctx, getClicksByBrowser, arg.ShortUrlID, arg.ClickedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetClicksByBrowserRow{}
	for rows.Next() {
		var i GetClicksByBrowserRow
		if err := rows.Scan(&i.Browser, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClicksByCity = `-- name: GetClicksByCity :many
SELECT city, country, COUNT(*) as clicks FROM clicks WHERE short_url_id = $1 AND clicked_at >= $2 AND city IS NOT NULL GROUP BY city, country ORDER BY clicks DESC LIMIT $3
`

type GetClicksByCityParams struct {
	ShortUrlID int64              `json:"short_url_id"`
	ClickedAt  pgtype.Timestamptz `json:"clicked_at"`
	Limit      int32              `json:"limit"`
}

type GetClicksByCityRow struct {
	City    pgtype.Text `json:"city"`
	Country pgtype.Text `json:"country"`
	Clicks  int64       `json:"clicks"`
}

func (q *Queries) GetClicksByCity(ctx context.Context, arg GetClicksByCityParams) ([]GetClicksByCityRow, error) {
	rows, err := q.db.Query(ctx, getClicksByCity, arg.ShortUrlID, arg.ClickedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetClicksByCityRow{}
	for rows.Next() {
		var i GetClicksByCityRow
		if err := rows.Scan(&i.City, &i.Country, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClicksByCountry = `-- name: GetClicksByCountry :many
SELECT country, COUNT(*) as clicks FROM clicks WHERE short_url_id = $1 AND clicked_at >= $2 GROUP BY country ORDER BY clicks DESC LIMIT $3
`

type GetClicksByCountryParams struct {
	ShortUrlID int64              `json:"short_url_id"`
	ClickedAt  pgtype.Timestamptz `json:"clicked_at"`
	Limit      int32              `json:"limit"`
}

type GetClicksByCountryRow struct {
	Country pgtype.Text `json:"country"`
	Clicks  int64       `json:"clicks"`
}

func (q *Queries) GetClicksByCountry(ctx context.Context, arg GetClicksByCountryParams) ([]GetClicksByCountryRow, error) {
	rows, err := q.db.Query(ctx, getClicksByCountry, arg.ShortUrlID, arg.ClickedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetClicksByCountryRow{}
	for rows.Next() {
		var i GetClicksByCountryRow
		if err := rows.Scan(&i.Country, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClicksByDevice = `-- name: GetClicksByDevice :many
SELECT device_type, COUNT(*) as clicks FROM clicks WHERE short_url_id = $1 AND clicked_at >= $2 GROUP BY device_type
`

type GetClicksByDeviceParams struct {
	ShortUrlID int64              `json:"short_url_id"`
	ClickedAt  pgtype.Timestamptz `json:"clicked_at"`
}

type GetClicksByDeviceRow struct {
	DeviceType pgtype.Text `json:"device_type"`
	Clicks     int64       `json:"clicks"`
}

func (q *Queries) GetClicksByDevice(ctx context.Context, arg GetClicksByDeviceParams) ([]GetClicksByDeviceRow, error) {
	rows, err := q.db.Query(ctx, getClicksByDevice, arg.ShortUrlID, arg.ClickedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetClicksByDeviceRow{}
	for rows.Next() {
		var i GetClicksByDeviceRow
		if err := rows.Scan(&i.DeviceType, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClicksByOS = `-- name: GetClicksByOS :many
SELECT os, COUNT(*) as clicks FROM clicks WHERE short_url_id = $1 AND clicked_at >= $2 GROUP BY os ORDER BY clicks DESC
`

type GetClicksByOSParams struct {
	ShortUrlID int64              `json:"short_url_id"`
	ClickedAt  pgtype.Timestamptz `json:"clicked_at"`
}

type GetClicksByOSRow struct {
	Os     pgtype.Text `json:"os"`
	Clicks int64       `json:"clicks"`
}

func (q *Queries) GetClicksByOS(ctx context.Context, arg GetClicksByOSParams) ([]GetClicksByOSRow, error) {
	rows, err := q.db.Query(ctx, getClicksByOS, arg.ShortUrlID, arg.ClickedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetClicksByOSRow{}
	for rows.Next() {
		var i GetClicksByOSRow
		if err := rows.Scan(&i.Os, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClicksByShortURLID = `-- name: GetClicksByShortURLID :many
SELECT id, short_url_id, clicked_at, ip_hash, country, city, region, browser, os, device_type, referrer, referrer_domain, utm_source, utm_medium, utm_campaign, is_unique, is_bot FROM clicks WHERE short_url_id = $1 ORDER BY clicked_at DESC LIMIT $2 OFFSET $3
`

type GetClicksByShortURLIDParams struct {
	ShortUrlID int64 `json:"short_url_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) GetClicksByShortURLID(ctx context.Context, arg GetClicksByShortURLIDParams) ([]Click, error) {
	rows, err := q.db.Query(ctx, getClicksByShortURLID, arg.ShortUrlID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Click{}
	for rows.Next() {
		var i Click
		if err := rows.Scan(
			&i.ID,
			&i.ShortUrlID,
			&i.ClickedAt,
			&i.IpHash,
			&i.Country,
			&i.City,
			&i.Region,
			&i.Browser,
			&i.Os,
			&i.DeviceType,
			&i.Referrer,
			&i.ReferrerDomain,
			&i.UtmSource,
			&i.UtmMedium,
			&i.UtmCampaign,
			&i.IsUnique,
			&i.IsBot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClicksSummary = `-- name: GetClicksSummary :one
SELECT
    COUNT(*) as total_clicks,
    COUNT(*) FILTER (WHERE is_unique = TRUE) as unique_clicks,
    COUNT(*) FILTER (WHERE is_bot = TRUE) as bot_clicks
FROM clicks
WHERE short_url_id = $1 AND clicked_at >= $2
`

type GetClicksSummaryParams struct {
	ShortUrlID int64              `json:"short_url_id"`
	ClickedAt  pgtype.Timestamptz `json:"clicked_at"`
}

type GetClicksSummaryRow struct {
	TotalClicks  int64 `json:"total_clicks"`
	UniqueClicks int64 `json:"unique_clicks"`
	BotClicks    int64 `json:"bot_clicks"`
}

func (q *Queries) GetClicksSummary(ctx context.Context, arg GetClicksSummaryParams) (GetClicksSummaryRow, error) {
	row := q.db.QueryRow(ctx, getClicksSummary, arg.ShortUrlID, arg.ClickedAt)
	var i GetClicksSummaryRow
	err := row.Scan(&i.TotalClicks, &i.UniqueClicks, &i.BotClicks)
	return i, err
}

const getClicksSummaryAllTime = `-- name: GetClicksSummaryAllTime :one
SELECT
    COUNT(*) as total_clicks,
    COUNT(*) FILTER (WHERE is_unique = TRUE) as unique_clicks,
    COUNT(*) FILTER (WHERE is_bot = TRUE) as bot_clicks
FROM clicks
WHERE short_url_id = $1
`

type GetClicksSummaryAllTimeRow struct {
	TotalClicks  int64 `json:"total_clicks"`
	UniqueClicks int64 `json:"unique_clicks"`
	BotClicks    int64 `json:"bot_clicks"`
}

func (q *Queries) GetClicksSummaryAllTime(ctx context.Context, shortUrlID int64) (GetClicksSummaryAllTimeRow, error) {
	row := q.db.QueryRow(ctx, getClicksSummaryAllTime, shortUrlID)
	var i GetClicksSummaryAllTimeRow
	err := row.Scan(&i.TotalClicks, &i.UniqueClicks, &i.BotClicks)
	return i, err
}

const getClicksTimeseries = `-- name: GetClicksTimeseries :many
SELECT DATE_TRUNC('day', clicked_at)::TIMESTAMPTZ as date, COUNT(*) as clicks FROM clicks WHERE short_url_id = $1 AND clicked_at >= $2 GROUP BY DATE_TRUNC('day', clicked_at) ORDER BY date
`

type GetClicksTimeseriesParams struct {
	ShortUrlID int64              `json:"short_url_id"`
	ClickedAt  pgtype.Timestamptz `json:"clicked_at"`
}

type GetClicksTimeseriesRow struct {
	Date   pgtype.Timestamptz `json:"date"`
	Clicks int64              `json:"clicks"`
}

func (q *Queries) GetClicksTimeseries(ctx context.Context, arg GetClicksTimeseriesParams) ([]GetClicksTimeseriesRow, error) {
	rows, err := q.db.Query(ctx, getClicksTimeseries, arg.ShortUrlID, arg.ClickedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetClicksTimeseriesRow{}
	for rows.Next() {
		var i GetClicksTimeseriesRow
		if err := rows.Scan(&i.Date, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClicksTimeseriesHourly = `-- name: GetClicksTimeseriesHourly :many
SELECT DATE_TRUNC('hour', clicked_at)::TIMESTAMPTZ as date, COUNT(*) as clicks FROM clicks WHERE short_url_id = $1 AND clicked_at >= $2 GROUP BY DATE_TRUNC('hour', clicked_at) ORDER BY date
`

type GetClicksTimeseriesHourlyParams struct {
	ShortUrlID int64              `json:"short_url_id"`
	ClickedAt  pgtype.Timestamptz `json:"clicked_at"`
}

type GetClicksTimeseriesHourlyRow struct {
	Date   pgtype.Timestamptz `json:"date"`
	Clicks int64              `json:"clicks"`
}

func (q *Queries) GetClicksTimeseriesHourly(ctx context.Context, arg GetClicksTimeseriesHourlyParams) ([]GetClicksTimeseriesHourlyRow, error) {
	rows, err := q.db.Query(ctx, getClicksTimeseriesHourly, arg.ShortUrlID, arg.ClickedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetClicksTimeseriesHourlyRow{}
	for rows.Next() {
		var i GetClicksTimeseriesHourlyRow
		if err := rows.Scan(&i.Date, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopCampaigns = `-- name: GetTopCampaigns :many
SELECT utm_campaign, COUNT(*) as clicks FROM clicks WHERE short_url_id = $1 AND clicked_at >= $2 AND utm_campaign IS NOT NULL GROUP BY utm_campaign ORDER BY clicks DESC LIMIT $3
`

type GetTopCampaignsParams struct {
	ShortUrlID int64              `json:"short_url_id"`
	ClickedAt  pgtype.Timestamptz `json:"clicked_at"`
	Limit      int32              `json:"limit"`
}

type GetTopCampaignsRow struct {
	UtmCampaign pgtype.Text `json:"utm_campaign"`
	Clicks      int64       `json:"clicks"`
}

func (q *Queries) GetTopCampaigns(ctx context.Context, arg GetTopCampaignsParams) ([]GetTopCampaignsRow, error) {
	rows, err := q.db.Query(ctx, getTopCampaigns, arg.ShortUrlID, arg.ClickedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopCampaignsRow{}
	for rows.Next() {
		var i GetTopCampaignsRow
		if err := rows.Scan(&i.UtmCampaign, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopReferrers = `-- name: GetTopReferrers :many
SELECT referrer_domain, COUNT(*) as clicks FROM clicks WHERE short_url_id = $1 AND clicked_at >= $2 AND referrer_domain IS NOT NULL GROUP BY referrer_domain ORDER BY clicks DESC LIMIT $3
`

type GetTopReferrersParams struct {
	ShortUrlID int64              `json:"short_url_id"`
	ClickedAt  pgtype.Timestamptz `json:"clicked_at"`
	Limit      int32              `json:"limit"`
}

type GetTopReferrersRow struct {
	ReferrerDomain pgtype.Text `json:"referrer_domain"`
	Clicks         int64       `json:"clicks"`
}

func (q *Queries) GetTopReferrers(ctx context.Context, arg GetTopReferrersParams) ([]GetTopReferrersRow, error) {
	rows, err := q.db.Query(ctx, getTopReferrers, arg.ShortUrlID, arg.ClickedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopReferrersRow{}
	for rows.Next() {
		var i GetTopReferrersRow
		if err := rows.Scan(&i.ReferrerDomain, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertClick = `-- name: InsertClick :exec
INSERT INTO clicks (short_url_id, ip_hash, country, city, region, browser, os, device_type, referrer, referrer_domain, utm_source, utm_medium, utm_campaign, is_unique, is_bot)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
`

type InsertClickParams struct {
	ShortUrlID     int64       `json:"short_url_id"`
	IpHash         string      `json:"ip_hash"`
	Country        pgtype.Text `json:"country"`
	City           pgtype.Text `json:"city"`
	Region         pgtype.Text `json:"region"`
	Browser        pgtype.Text `json:"browser"`
	Os             pgtype.Text `json:"os"`
	DeviceType     pgtype.Text `json:"device_type"`
	Referrer       pgtype.Text `json:"referrer"`
	ReferrerDomain pgtype.Text `json:"referrer_domain"`
	UtmSource      pgtype.Text `json:"utm_source"`
	UtmMedium      pgtype.Text `json:"utm_medium"`
	UtmCampaign    pgtype.Text `json:"utm_campaign"`
	IsUnique       pgtype.Bool `json:"is_unique"`
	IsBot          pgtype.Bool `json:"is_bot"`
}

func (q *Queries) InsertClick(ctx context.Context, arg InsertClickParams) error {
	_, err := q.db.Exec(ctx, insertClick,
		arg.ShortUrlID,
		arg.IpHash,
		arg.Country,
		arg.City,
		arg.Region,
		arg.Browser,
		arg.Os,
		arg.DeviceType,
		arg.Referrer,
		arg.ReferrerDomain,
		arg.UtmSource,
		arg.UtmMedium,
		arg.UtmCampaign,
		arg.IsUnique,
		arg.IsBot,
	)
	return err
}
