// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_short_url.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createShortURL = `-- name: CreateShortURL :one
INSERT INTO short_urls (code, long_url, owner_id)
VALUES ($1, $2, $3)
RETURNING id, code, long_url, owner_id, created_at, updated_at
`

type CreateShortURLParams struct {
	Code    string      `json:"code"`
	LongUrl string      `json:"long_url"`
	OwnerID pgtype.Int8 `json:"owner_id"`
}

type CreateShortURLRow struct {
	ID        int64              `json:"id"`
	Code      string             `json:"code"`
	LongUrl   string             `json:"long_url"`
	OwnerID   pgtype.Int8        `json:"owner_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateShortURL(ctx context.Context, arg CreateShortURLParams) (CreateShortURLRow, error) {
	row := q.db.QueryRow(ctx, createShortURL, arg.Code, arg.LongUrl, arg.OwnerID)
	var i CreateShortURLRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.LongUrl,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateShortURLCode = `-- name: UpdateShortURLCode :one
UPDATE short_urls
SET code = $2
WHERE id = $1
RETURNING id, code, long_url, owner_id, created_at, updated_at
`

type UpdateShortURLCodeParams struct {
	ID   int64  `json:"id"`
	Code string `json:"code"`
}

type UpdateShortURLCodeRow struct {
	ID        int64              `json:"id"`
	Code      string             `json:"code"`
	LongUrl   string             `json:"long_url"`
	OwnerID   pgtype.Int8        `json:"owner_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateShortURLCode(ctx context.Context, arg UpdateShortURLCodeParams) (UpdateShortURLCodeRow, error) {
	row := q.db.QueryRow(ctx, updateShortURLCode, arg.ID, arg.Code)
	var i UpdateShortURLCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.LongUrl,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
