// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_short_url.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countURLsByOwner = `-- name: CountURLsByOwner :one
SELECT COUNT(*) FROM short_urls
WHERE owner_type = $1 AND owner_id = $2 AND is_deleted = FALSE
`

type CountURLsByOwnerParams struct {
	OwnerType OwnerTypeEnum `json:"owner_type"`
	OwnerID   string        `json:"owner_id"`
}

func (q *Queries) CountURLsByOwner(ctx context.Context, arg CountURLsByOwnerParams) (int64, error) {
	row := q.db.QueryRow(ctx, countURLsByOwner, arg.OwnerType, arg.OwnerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countURLsCreatedThisMonth = `-- name: CountURLsCreatedThisMonth :one
SELECT COUNT(*) FROM short_urls
WHERE owner_id = $1
AND created_at >= date_trunc('month', CURRENT_TIMESTAMP)
AND is_deleted = FALSE
`

func (q *Queries) CountURLsCreatedThisMonth(ctx context.Context, ownerID string) (int64, error) {
	row := q.db.QueryRow(ctx, countURLsCreatedThisMonth, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createShortURL = `-- name: CreateShortURL :one
INSERT INTO short_urls (code, long_url, owner_type, owner_id, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, code, long_url, owner_type, owner_id, expires_at, created_at, updated_at
`

type CreateShortURLParams struct {
	Code      string             `json:"code"`
	LongUrl   string             `json:"long_url"`
	OwnerType OwnerTypeEnum      `json:"owner_type"`
	OwnerID   string             `json:"owner_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type CreateShortURLRow struct {
	ID        int64              `json:"id"`
	Code      string             `json:"code"`
	LongUrl   string             `json:"long_url"`
	OwnerType OwnerTypeEnum      `json:"owner_type"`
	OwnerID   string             `json:"owner_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateShortURL(ctx context.Context, arg CreateShortURLParams) (CreateShortURLRow, error) {
	row := q.db.QueryRow(ctx, createShortURL,
		arg.Code,
		arg.LongUrl,
		arg.OwnerType,
		arg.OwnerID,
		arg.ExpiresAt,
	)
	var i CreateShortURLRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.LongUrl,
		&i.OwnerType,
		&i.OwnerID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClicksByShortURLID = `-- name: DeleteClicksByShortURLID :exec
DELETE FROM clicks WHERE short_url_id = $1
`

func (q *Queries) DeleteClicksByShortURLID(ctx context.Context, shortUrlID int64) error {
	_, err := q.db.Exec(ctx, deleteClicksByShortURLID, shortUrlID)
	return err
}

const getShortURLByCode = `-- name: GetShortURLByCode :one
SELECT id, code, long_url, owner_type, owner_id, is_active, is_deleted, expires_at, created_at, updated_at
FROM short_urls
WHERE code = $1 AND is_deleted = FALSE
`

func (q *Queries) GetShortURLByCode(ctx context.Context, code string) (ShortUrl, error) {
	row := q.db.QueryRow(ctx, getShortURLByCode, code)
	var i ShortUrl
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.LongUrl,
		&i.OwnerType,
		&i.OwnerID,
		&i.IsActive,
		&i.IsDeleted,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShortURLsByOwner = `-- name: GetShortURLsByOwner :many
SELECT id, code, long_url, owner_type, owner_id, is_active, is_deleted, expires_at, created_at, updated_at
FROM short_urls
WHERE owner_type = $1 AND owner_id = $2 AND is_deleted = FALSE
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type GetShortURLsByOwnerParams struct {
	OwnerType OwnerTypeEnum `json:"owner_type"`
	OwnerID   string        `json:"owner_id"`
	Limit     int32         `json:"limit"`
	Offset    int32         `json:"offset"`
}

func (q *Queries) GetShortURLsByOwner(ctx context.Context, arg GetShortURLsByOwnerParams) ([]ShortUrl, error) {
	rows, err := q.db.Query(ctx, getShortURLsByOwner,
		arg.OwnerType,
		arg.OwnerID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShortUrl{}
	for rows.Next() {
		var i ShortUrl
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.LongUrl,
			&i.OwnerType,
			&i.OwnerID,
			&i.IsActive,
			&i.IsDeleted,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getURLByCodeAndOwner = `-- name: GetURLByCodeAndOwner :one
SELECT id, code, long_url, owner_type, owner_id, is_active, is_deleted, expires_at, created_at, updated_at
FROM short_urls
WHERE code = $1 AND owner_type = $2 AND owner_id = $3 AND is_deleted = FALSE
`

type GetURLByCodeAndOwnerParams struct {
	Code      string        `json:"code"`
	OwnerType OwnerTypeEnum `json:"owner_type"`
	OwnerID   string        `json:"owner_id"`
}

func (q *Queries) GetURLByCodeAndOwner(ctx context.Context, arg GetURLByCodeAndOwnerParams) (ShortUrl, error) {
	row := q.db.QueryRow(ctx, getURLByCodeAndOwner, arg.Code, arg.OwnerType, arg.OwnerID)
	var i ShortUrl
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.LongUrl,
		&i.OwnerType,
		&i.OwnerID,
		&i.IsActive,
		&i.IsDeleted,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteURL = `-- name: SoftDeleteURL :exec
UPDATE short_urls
SET is_deleted = TRUE
WHERE code = $1 AND owner_type = $2 AND owner_id = $3 AND is_deleted = FALSE
`

type SoftDeleteURLParams struct {
	Code      string        `json:"code"`
	OwnerType OwnerTypeEnum `json:"owner_type"`
	OwnerID   string        `json:"owner_id"`
}

func (q *Queries) SoftDeleteURL(ctx context.Context, arg SoftDeleteURLParams) error {
	_, err := q.db.Exec(ctx, softDeleteURL, arg.Code, arg.OwnerType, arg.OwnerID)
	return err
}

const toggleURLActive = `-- name: ToggleURLActive :exec
UPDATE short_urls
SET is_active = NOT is_active
WHERE code = $1 AND owner_type = $2 AND owner_id = $3 AND is_deleted = FALSE
`

type ToggleURLActiveParams struct {
	Code      string        `json:"code"`
	OwnerType OwnerTypeEnum `json:"owner_type"`
	OwnerID   string        `json:"owner_id"`
}

func (q *Queries) ToggleURLActive(ctx context.Context, arg ToggleURLActiveParams) error {
	_, err := q.db.Exec(ctx, toggleURLActive, arg.Code, arg.OwnerType, arg.OwnerID)
	return err
}

const transferAnonymousURLsToUser = `-- name: TransferAnonymousURLsToUser :exec
UPDATE short_urls
SET owner_type = 'user', owner_id = $2, expires_at = NULL
WHERE owner_type = 'anonymous' AND owner_id = $1
`

type TransferAnonymousURLsToUserParams struct {
	OwnerID   string `json:"owner_id"`
	OwnerID_2 string `json:"owner_id_2"`
}

func (q *Queries) TransferAnonymousURLsToUser(ctx context.Context, arg TransferAnonymousURLsToUserParams) error {
	_, err := q.db.Exec(ctx, transferAnonymousURLsToUser, arg.OwnerID, arg.OwnerID_2)
	return err
}

const transferAnonymousURLsToUserWithLimit = `-- name: TransferAnonymousURLsToUserWithLimit :exec
UPDATE short_urls
SET owner_type = 'user', owner_id = $2, expires_at = NULL
WHERE id IN (
    SELECT s.id FROM short_urls s
    WHERE s.owner_type = 'anonymous' AND s.owner_id = $1 AND s.is_deleted = FALSE
    ORDER BY s.created_at ASC
    LIMIT $3
)
`

type TransferAnonymousURLsToUserWithLimitParams struct {
	OwnerID   string `json:"owner_id"`
	OwnerID_2 string `json:"owner_id_2"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) TransferAnonymousURLsToUserWithLimit(ctx context.Context, arg TransferAnonymousURLsToUserWithLimitParams) error {
	_, err := q.db.Exec(ctx, transferAnonymousURLsToUserWithLimit, arg.OwnerID, arg.OwnerID_2, arg.Limit)
	return err
}

const updateLongURL = `-- name: UpdateLongURL :one
UPDATE short_urls
SET long_url = $4, expires_at = $5
WHERE code = $1 AND owner_type = $2 AND owner_id = $3 AND is_deleted = FALSE
RETURNING id, code, long_url, owner_type, owner_id, is_active, is_deleted, expires_at, created_at, updated_at
`

type UpdateLongURLParams struct {
	Code      string             `json:"code"`
	OwnerType OwnerTypeEnum      `json:"owner_type"`
	OwnerID   string             `json:"owner_id"`
	LongUrl   string             `json:"long_url"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpdateLongURL(ctx context.Context, arg UpdateLongURLParams) (ShortUrl, error) {
	row := q.db.QueryRow(ctx, updateLongURL,
		arg.Code,
		arg.OwnerType,
		arg.OwnerID,
		arg.LongUrl,
		arg.ExpiresAt,
	)
	var i ShortUrl
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.LongUrl,
		&i.OwnerType,
		&i.OwnerID,
		&i.IsActive,
		&i.IsDeleted,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateShortURLCode = `-- name: UpdateShortURLCode :one
UPDATE short_urls
SET code = $2
WHERE id = $1
RETURNING id, code, long_url, owner_type, owner_id, expires_at, created_at, updated_at
`

type UpdateShortURLCodeParams struct {
	ID   int64  `json:"id"`
	Code string `json:"code"`
}

type UpdateShortURLCodeRow struct {
	ID        int64              `json:"id"`
	Code      string             `json:"code"`
	LongUrl   string             `json:"long_url"`
	OwnerType OwnerTypeEnum      `json:"owner_type"`
	OwnerID   string             `json:"owner_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateShortURLCode(ctx context.Context, arg UpdateShortURLCodeParams) (UpdateShortURLCodeRow, error) {
	row := q.db.QueryRow(ctx, updateShortURLCode, arg.ID, arg.Code)
	var i UpdateShortURLCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.LongUrl,
		&i.OwnerType,
		&i.OwnerID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
