// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ShortUrl struct {
	ID        int64              `json:"id"`
	Code      string             `json:"code"`
	LongUrl   string             `json:"long_url"`
	OwnerID   pgtype.Int8        `json:"owner_id"`
	IsActive  bool               `json:"is_active"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
