// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type OwnerTypeEnum string

const (
	OwnerTypeEnumUser      OwnerTypeEnum = "user"
	OwnerTypeEnumAnonymous OwnerTypeEnum = "anonymous"
)

func (e *OwnerTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OwnerTypeEnum(s)
	case string:
		*e = OwnerTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for OwnerTypeEnum: %T", src)
	}
	return nil
}

type NullOwnerTypeEnum struct {
	OwnerTypeEnum OwnerTypeEnum `json:"owner_type_enum"`
	Valid         bool          `json:"valid"` // Valid is true if OwnerTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOwnerTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.OwnerTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OwnerTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOwnerTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OwnerTypeEnum), nil
}

func (e OwnerTypeEnum) Valid() bool {
	switch e {
	case OwnerTypeEnumUser,
		OwnerTypeEnumAnonymous:
		return true
	}
	return false
}

func AllOwnerTypeEnumValues() []OwnerTypeEnum {
	return []OwnerTypeEnum{
		OwnerTypeEnumUser,
		OwnerTypeEnumAnonymous,
	}
}

type SubscriptionTier string

const (
	SubscriptionTierFree     SubscriptionTier = "free"
	SubscriptionTierPro      SubscriptionTier = "pro"
	SubscriptionTierBusiness SubscriptionTier = "business"
)

func (e *SubscriptionTier) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubscriptionTier(s)
	case string:
		*e = SubscriptionTier(s)
	default:
		return fmt.Errorf("unsupported scan type for SubscriptionTier: %T", src)
	}
	return nil
}

type NullSubscriptionTier struct {
	SubscriptionTier SubscriptionTier `json:"subscription_tier"`
	Valid            bool             `json:"valid"` // Valid is true if SubscriptionTier is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubscriptionTier) Scan(value interface{}) error {
	if value == nil {
		ns.SubscriptionTier, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubscriptionTier.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubscriptionTier) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubscriptionTier), nil
}

func (e SubscriptionTier) Valid() bool {
	switch e {
	case SubscriptionTierFree,
		SubscriptionTierPro,
		SubscriptionTierBusiness:
		return true
	}
	return false
}

func AllSubscriptionTierValues() []SubscriptionTier {
	return []SubscriptionTier{
		SubscriptionTierFree,
		SubscriptionTierPro,
		SubscriptionTierBusiness,
	}
}

type Click struct {
	ID             int64              `json:"id"`
	ShortUrlID     int64              `json:"short_url_id"`
	ClickedAt      pgtype.Timestamptz `json:"clicked_at"`
	IpHash         string             `json:"ip_hash"`
	Country        pgtype.Text        `json:"country"`
	City           pgtype.Text        `json:"city"`
	Region         pgtype.Text        `json:"region"`
	Browser        pgtype.Text        `json:"browser"`
	Os             pgtype.Text        `json:"os"`
	DeviceType     pgtype.Text        `json:"device_type"`
	Referrer       pgtype.Text        `json:"referrer"`
	ReferrerDomain pgtype.Text        `json:"referrer_domain"`
	UtmSource      pgtype.Text        `json:"utm_source"`
	UtmMedium      pgtype.Text        `json:"utm_medium"`
	UtmCampaign    pgtype.Text        `json:"utm_campaign"`
	IsUnique       pgtype.Bool        `json:"is_unique"`
	IsBot          pgtype.Bool        `json:"is_bot"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ShortUrl struct {
	ID        int64              `json:"id"`
	Code      string             `json:"code"`
	LongUrl   string             `json:"long_url"`
	OwnerType OwnerTypeEnum      `json:"owner_type"`
	OwnerID   string             `json:"owner_id"`
	IsActive  bool               `json:"is_active"`
	IsDeleted bool               `json:"is_deleted"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	// 0 = email/password, 1 = google
	LoginType          int16              `json:"login_type"`
	GoogleID           pgtype.Text        `json:"google_id"`
	Name               pgtype.Text        `json:"name"`
	AvatarUrl          pgtype.Text        `json:"avatar_url"`
	Tier               SubscriptionTier   `json:"tier"`
	StripeCustomerID   pgtype.Text        `json:"stripe_customer_id"`
	SubscriptionEndsAt pgtype.Timestamptz `json:"subscription_ends_at"`
}
